# Generated by Django 4.0 on 2022-01-10 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='column_id',
            new_name='column',
        ),
    ]
